---
- hosts: aws_e_1

  pre_tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  # bootstrap python onto server
  #
  # pre_tasks:
  # - name: Install python 2 if not there
  #   raw: |
  #     test -e /usr/bin/python || \
  #     (apt -y update && apt install -y python-simplejson)
  #   register: output
  #   changed_when: output.stdout|trim() != ""
  # - name: Install sudo if not there
  #   raw: |
  #     test -e /usr/bin/sudo || apt install -y sudo
  #   register: output
  #   changed_when: output.stdout|trim() != ""
    
  become: yes
  become_user: root
  gather_facts: False



  roles:
  - core
  # - mogreps


